stages:
  - build-docker
  - deploy

variables:
  DOCKER_DRIVER: overlay2
  IMAGE_NAME: adminjogetids/rag-frontend
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""

before_script:
  - echo "🚀 Start CI/CD pipeline"

docker_build:
  stage: build-docker
  image: docker:24.0.5
  services:
    - docker:dind
  script:
    - echo "🚀 Login to Docker Hub"
    - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
    - echo "🚀 Build Docker image"
    - docker build \
        --build-arg VITE_GOOGLE_CLIENT_ID=$VITE_GOOGLE_CLIENT_ID \
        --build-arg VITE_BASE_URL=/api \
        -t $DOCKERHUB_USERNAME/$IMAGE_NAME:latest .
    - echo "🚀 Push Docker image"
    - docker push $DOCKERHUB_USERNAME/$IMAGE_NAME:latest
  only:
    - main

deploy_vps:
  stage: deploy
  image: alpine:latest
  before_script:
    - apk add --no-cache openssh
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - eval $(ssh-agent -s)
    - ssh-add ~/.ssh/id_rsa
  script:
    - echo "🔑 Deploying to VPS"
    - ssh -o StrictHostKeyChecking=no $VPS_USER@$VPS_HOST "
        cd ~/project/ai-rag &&
        docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD &&
        docker compose pull $DOCKERHUB_USERNAME/$IMAGE_NAME:latest &&
        docker compose up -d
      "
